on:
  push:
    tags:
    - "*"
name: build, test and publish production
jobs:
  publish_production:
    name: build, test and publish production
    runs-on: ubuntu-latest
    container: node:latest
    steps:
    - uses: actions/checkout@v1
      with:
        fetch-depth: 1
    - name: install
      run: npm ci
      env:
        NPM_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: test
      run: npm test
    - name: build
      run: npm run build
    - name: publish production
      run: |
        export NPM_TOKEN=$GITHUB_TOKEN
        npm publish
      env:
        GH_EMAIL: ${{ secrets.GH_EMAIL }}
        GH_USER: ${{ secrets.GH_USER }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
