on:
  push:
    branches:
    - master
env:
  NPM_TOKEN: ${{ secrets.GITHUB_TOKEN }}
name: build, test and publish beta
jobs:
  publish_beta:
    name: build, test and publish beta
    runs-on: ubuntu-latest
    container: node:latest
    steps:
    - uses: actions/checkout@v1
      with:
        fetch-depth: 1
    - name: install
      uses: ./.github/actions/run-with-gpr-auth
      with:
        run: |
          whoami
          ls -la /usr/local/lib/node_modules/npm
          npm -g bin
          npm ci
    - name: test
      run: npm test
    - name: build
      run: npm run build
    - name: publish beta
      uses: ./.github/actions/run-with-gpr-auth
      with:
        run: |
          version=`node .github/workflows/getVersion.js`
          npm --no-git-tag-version version $version
          npm publish --tag alpha
