on:
  push:
    branches:
      - master
name: build, test and publish beta
jobs:
  publish_beta:
    name: build, test and publish beta
    runs-on: ubuntu-latest
    container: node:latest
    steps:
    - name: install
      uses: actions/npm@master
      with:
        args: ci
    - name: test
      uses: actions/npm@master
      with:
        args: test
    - name: build
      uses: actions/npm@master
      with:
        args: run build
    - name: filter branch master
      uses: actions/bin/filter@master
      with:
        args: branch master
    - name: publish beta
      run: |
        export NPM_TOKEN=$GITHUB_TOKEN
        version=`node .github/workflows/getVersion.js`
        npm --no-git-tag-version version $version
        npm publish
        npm dist-tag add @andrewbranch/definitely-not-slow@$version alpha
      shell: bash
      env:
        GH_EMAIL: ${{ secrets.GH_EMAIL }}
        GH_USER: ${{ secrets.GH_USER }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
