on:
  push:
    tags:
    - "*"
env:
  NPM_TOKEN: ${{ secrets.GITHUB_TOKEN }}
name: build, test and publish production
jobs:
  publish_production:
    name: build, test and publish production
    runs-on: ubuntu-latest
    container: node:latest
    steps:
    - uses: actions/checkout@v1
      with:
        fetch-depth: 1
    - name: install
      run: npm ci
    - name: test
      run: npm test
    - name: build
      run: npm run build
    - name: publish production
      run: |
        npm publish
